### ISSUE TITLE
model for diversity

### ISSUE THREAD

**Issue by wcornwell** [Josh-Lee1/JL_honours#1]
- maybe using [hill numbers](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.12613#:~:text=Hill%20numbers%20are%20parameterized%20by,diversity%20(q%20%3D%202).) 

- probably model will be from `lme4`

- first model just using burnt/unburnt

- later model using veg variable to see what aspect of the fire is important

**Comment by Josh-Lee1** [comment]
Thanks Will. 
I have run iNEXT and have an object with all my diversity values. But I'm guessing we will extract one value (either shannon or Simpson) to use in the model?

**Comment by wcornwell** [comment]
yes i think so

**Comment by wcornwell** [comment]
![image](https://user-images.githubusercontent.com/5534161/107162885-2a754100-69fa-11eb-982d-37107167445f.png)

**Comment by wcornwell** [comment]
```{r}
#make model
shandiv<- lmer(Shannon_diversity ~ Formation * Fire +(1|Location), data = div4mod)
shandiv2<- lmer(Shannon_diversity ~ Formation + (1|Location), data = div4mod)

summary(shandiv)
plot(shandiv)
anova(shandiv2,shandiv)

library(sjPlot)
library(sjmisc)
plot_model(shandiv, type = "int")
```

**Comment by Josh-Lee1** [comment]
Thanks Will. 
I got pretty close! 
Also just to clarify some result interpreting: 
iNEXT gave me different Shannon and Simpson than the vegan package, is that because iNEXT is using the Hill numbers to estimate a new diversity metric? 
and is the chi squared value out of the anova(shandiv2,shandiv) line suggesting that diversity is correlated with Formation and Fire?

**Comment by wcornwell** [comment]
the `anova` line compares a model with "Fire" to a model without "Fire" so it's a way to test whether "Fire" adds significantly to the model.  see here: http://environmentalcomputing.net/mixed-models-1/

**Comment by Josh-Lee1** [comment]
Ok cool think I've got that. 
Thanks
