### ISSUE TITLE
Density

### ISSUE THREAD

**Issue by Josh-Lee1** [Josh-Lee1/JL_honours#3]
I have run through code in my distance script which I thought would give me a density value for birds at each site but i'm missing an output.
I am following the advice below and have **1. Summary statistics** but not 2. Abundance or 3. Density??

From Miller et al., 2016 https://www.biorxiv.org/content/10.1101/063891v1.full.pdf :
"When we supply data to ds in the “flatfile” format given above, ds will automatically calculate abundance estimates based on the survey information in the data.
...
This prints a rather large amount of information: first the detection function summary, then
three tables:
1. Summary statistics: giving the areas, covered areas, effort, number of observations, number of transects, encounter rate, its 2. standard error and coefficient of variation for each stratum. 
2. Abundance: giving estimates, standard errors, coefficients of variation, lower and upper confidence intervals and finally the degrees of freedom for each stratum’s abundance estimate. 
3. Density: lists the same statistics as Abundance but for a density estimate."

**Comment by Josh-Lee1** [comment]
@wcornwell

**Comment by wcornwell** [comment]
tough one!

**Comment by wcornwell** [comment]
i think it has to do with:

from the `ds` help file


> ###Details
>If abundance estimates are required then the data.frames region.table and sample.table must be supplied. If data >does not contain the columns Region.Label and Sample.Label then the data.frame obs.table must also be supplied. >Note that stratification only applies to abundance estimates and not at the detection function level.

> For more advanced abundance/density estimation please see the dht and dht2 functions.

> Examples of distance sampling analyses are available at http://examples.distancesampling.org/.

but should discuss...

**Comment by Josh-Lee1** [comment]
![image](https://user-images.githubusercontent.com/59299694/107187415-118c8000-6a3a-11eb-8db3-44b1c8447088.png)

> summary(abund.aov)
               Df Sum Sq Mean Sq F value Pr(>F)
Fire            1    257   256.7   0.998  0.321
Formation       1    199   198.6   0.772  0.382
Fire:Formation  1    184   183.6   0.713  0.401
Residuals      76  19555   257.3

**Comment by wcornwell** [comment]
Shouldn't this be a mixed model also?

**Comment by Josh-Lee1** [comment]
Yeah cool. I was just excited that I got abundance/density working. 

![image](https://user-images.githubusercontent.com/59299694/107202924-da749980-6a4e-11eb-8ea9-5dbd2e29a8ba.png)

Data: density
Models:
density.lmer2: Estimate_density ~ Formation + (1 | Location)
density.lmer: Estimate_density ~ Formation * Fire + (1 | Location)
              npar     AIC     BIC logLik deviance  Chisq Df Pr(>Chisq)
density.lmer2    4 -368.86 -359.33 188.43  -376.86                     
density.lmer     6 -367.63 -353.33 189.81  -379.63 2.7641  2     0.2511

**Comment by wcornwell** [comment]
ok so no effect of fire on density/abundance...
