### ISSUE TITLE
GLLVM

### ISSUE THREAD

**Issue by Josh-Lee1** [Josh-Lee1/JL_honours#4]
Hi @wcornwell, 

I am having a crack at putting the gllvm together by following this page: https://cran.r-project.org/web/packages/gllvm/vignettes/vignette1.html 

I have formatted my data to match that of the example data but then when I ran gllvm() I got this error:

Warning messages:
1: In gllvm.TMB(y, X = X, formula = formula, num.lv = num.lv, family = family,  :
  Error in optim(objr$par, objr$fn, objr$gr, method = "BFGS", control = list(reltol = reltol,  : 
  non-finite value supplied by optim

2: In gllvm(formula = Count ~ 1, data = df, family = "negative.binomial") :
  Algorithm converged to infinity, try other starting values or different method.

Having trouble diagnosing the problem from this error message. Any ideas??

Thanks, 
Josh

**Comment by wcornwell** [comment]
Optimization algo is cruzing out to infinity. Might not be fixable. But we can try.

**Comment by Josh-Lee1** [comment]
Hmmm ok... Does that mean we change the data or the model? 
I got the same error when I tried putting some predictor variables in there. 

gllvm(formula = Count ~ (Fire + Formation), data = df,  
      family = "negative.binomial")

**Comment by wcornwell** [comment]
How big is the tutorial dataset? It could be we just don't have enough sites for this method to fit...

**Comment by Josh-Lee1** [comment]
Sample data has 30 sites and 41 species.

**Comment by Josh-Lee1** [comment]
Mine is 80 sites 99 species

**Comment by wcornwell** [comment]
Push what you've got. I'll play around with it..

**Comment by Josh-Lee1** [comment]
Should be up to date!  
Thanks

**Comment by Josh-Lee1** [comment]
I did all the data wrangling in Traits.R and the model and example are in gllvm_play.R

**Comment by wcornwell** [comment]
try: 

```
gllvm(formula = Count ~ 1, data = df, family = "negative.binomial",
      control.start = list(starting.val = "zero", n.init = 1, jitter.var = 0, start.fit =
                             NULL, start.lvs = NULL, randomX.start = "res"))
```
it solves the infinity problem, but seems to be taking quite a while to fit...

**Comment by Josh-Lee1** [comment]
Still going...

**Comment by wcornwell** [comment]
I got a different error:

```
Error in `colnames<-`(`*tmp*`, value = colnames(out$lvs) <- paste("LV",  : 
  attempt to set 'colnames' on an object with less than two dimensions
```
may be pretty frustrating to try to use these cutting edge methods that haven't been well tested.

**Comment by Josh-Lee1** [comment]
Do you think mvabund::manyany will be a better option then?

**Comment by wcornwell** [comment]
higher probability of getting it working 🤷

**Comment by wcornwell** [comment]
when is next meeting with richard?  i think we should go back to basic questions before committing lots of time to getting one of these frameworks working.

**Comment by Josh-Lee1** [comment]
I got the GLLVM working!
Just running through it and trying to figure out what it's saying...

**Comment by wcornwell** [comment]
wow cool! push code, and i'll try to replicate here.

**Comment by Josh-Lee1** [comment]
Done

**Comment by wcornwell** [comment]
wow integer logicals!?!?!?

**Comment by Josh-Lee1** [comment]
I just do what Google tells me to do! haha

**Comment by wcornwell** [comment]
looks OK to me.  does Google know how to add the traits in?

**Comment by Josh-Lee1** [comment]
I have tips from Eve and she has traits as the next step. I will play with that now. I think I have to change how the trait data is formatted too.

**Comment by Josh-Lee1** [comment]
![heatmap](https://user-images.githubusercontent.com/59299694/107935095-09ea4f80-6fd5-11eb-8b65-d602ac2ec049.png)
![coefplot](https://user-images.githubusercontent.com/59299694/107935100-0b1b7c80-6fd5-11eb-94e2-4e0e0a6b74db.png)

**Comment by Josh-Lee1** [comment]
hey @wcornwell, 
So I'm having trouble running the code again by treatment. 
I've started a new script gllvm_treatments.R. 
up to line 87 is changing the formatting which looks like it's working but then running the model on line 91 gives me: 
Error in model.frame.default(formula, data = data) : 
  variable lengths differ (found for 'Litter.Depth') 
Everything should be up to date for you to pull. 
Thanks, 
Josh

**Comment by Josh-Lee1** [comment]
This has been fixed.

**Comment by wcornwell** [comment]
any new results?

**Comment by Josh-Lee1** [comment]
Are you available for a drop in today?
