### ISSUE TITLE
Density for Species

### ISSUE THREAD

**Issue by Josh-Lee1** [Josh-Lee1/JL_honours#6]
Hey @wcornwell, 
So I have pulled density estimates for each species from the model from the Distance package. 
However since we are going to split by habitat I'm thinking that I'm going to have to redo the models to isolate rainforest, dry sclerophyll and both. 
Because a species will have different density/abundance in a rainforest than a rainforest **and** ds forest right...?

Also I guess I need to also redo them for burnt/unburnt?

**Comment by Josh-Lee1** [comment]
![bothhabs](https://user-images.githubusercontent.com/59299694/109739216-624c5e80-7c1d-11eb-9606-32e02401308b.png)
![ds_only](https://user-images.githubusercontent.com/59299694/109739223-637d8b80-7c1d-11eb-8116-2115f4efeec8.png)
![rf_only](https://user-images.githubusercontent.com/59299694/109739225-637d8b80-7c1d-11eb-8b71-f2670062aacc.png)

**Comment by Josh-Lee1** [comment]
Hey Will, 
Figured a few things out. 
Only I'm still not sure whether I should have calculated density separately for each habitat type...

**Comment by Josh-Lee1** [comment]
![br_counts](https://user-images.githubusercontent.com/59299694/109768329-dce0a280-7c4c-11eb-8c0b-87a181954149.png)
![bs_counts](https://user-images.githubusercontent.com/59299694/109768334-de11cf80-7c4c-11eb-9e2e-71e25c94129b.png)
![ur_counts](https://user-images.githubusercontent.com/59299694/109768336-deaa6600-7c4c-11eb-85f3-79b140e06705.png)
![us_counts](https://user-images.githubusercontent.com/59299694/109768338-deaa6600-7c4c-11eb-95a4-0f94b519f391.png)

**Comment by Josh-Lee1** [comment]
Patches of Bell miners have thrown off the DS ones

**Comment by Josh-Lee1** [comment]
![br_counts](https://user-images.githubusercontent.com/59299694/109776641-ee2eac80-7c56-11eb-9d46-f7621c72255f.png)
![bs_counts](https://user-images.githubusercontent.com/59299694/109776648-ef5fd980-7c56-11eb-83d7-86cd823ea398.png)
![ur_counts](https://user-images.githubusercontent.com/59299694/109776650-eff87000-7c56-11eb-8b4b-7db92d03ae74.png)
![us_counts](https://user-images.githubusercontent.com/59299694/109776653-f0910680-7c56-11eb-90e8-9b5e30763415.png)

**Comment by Josh-Lee1** [comment]
![dry_counts](https://user-images.githubusercontent.com/59299694/110050944-031b5500-7da9-11eb-94f0-4307ef8ea5f6.png)
![rain_counts](https://user-images.githubusercontent.com/59299694/110050948-044c8200-7da9-11eb-9249-6efbab0ca33a.png)

**Comment by Josh-Lee1** [comment]
@wcornwell, 
Do you know how I can get the burnt/unburnt next to each other rather than overlapping?

**Comment by wcornwell** [comment]
https://stackoverflow.com/questions/6819047/ggplot2-offset-scatterplot-points

position = "dodge"

**Comment by wcornwell** [comment]
on an unrelated topic, do you know where to find the northern beaches black bittern?  (heading up that way tomorrow, and may try to stop and find it...)

**Comment by Josh-Lee1** [comment]
Thanks!
Do a lap of Mullet creek just south of the wetland. (They do fly through Warriwood wetland itself but viewing is less reliable).
There are some nice fallen trees hanging over the other side of the creek that they like to sit and hunt in. A good one I've seen them in twice is close to the bridge around here: -33.702067, 151.296303
