### ISSUE TITLE
Species Detectability

### ISSUE THREAD

**Issue by Josh-Lee1** [Josh-Lee1/JL_honours#8]
Hey @wcornwell, 
So still having trouble getting detectability for lewin's honeyeater... 
Im getting an error saying that there are covariate terms...?
I think it might have something to do with monotonicity of the data and having a problem fitting the curve to the LEHO data.
I have pushed my work in R/birds/Density_stuff/sp_detectability.R
Thanks, 
Josh

**Comment by wcornwell** [comment]
ok will try

**Comment by wcornwell** [comment]
```{r}
birds %>% filter(Species=="Wompoo Fruit-Dove")->oo
woom<-ds(data = oo,truncation = 400,key="hn",monotonicity = "strict")
oo %>%
  right_join(sites,c("Region.Label", "Location", "Formation", "Fire",  "Treatment","Sample.Label","Effort","Area"))->pp
out<-dht2(woom,flatfile=pp,strat_formula=~Treatment)
```

**Comment by wcornwell** [comment]
first load:

```{r}
library(tidyverse)
library(Distance)
library(mrds)
library(lme4)
library(sjPlot)
library(sjmisc)

#format data like species_density.R
birds <- read.csv("Data/Raw/Birds.csv")
birds$Treatment<- with(birds, paste0(Formation, Fire))
birds <- birds %>%
  group_by(Site) %>%
  mutate(species_richness = n_distinct(Species)) %>% 
  rename(distance = Distance) %>% 
  rename(Region.Label = Site) %>%
  as.data.frame()
birds$Area <- '628'
birds$Effort <- '1'
birds$Sample.Label <- '1'
birds$Area <- as.numeric(birds$Area)
birds$Effort <- as.numeric(birds$Effort)


#isolate Lewin's Honeyeater and add zeros
sites <- birds %>% 
  select(Region.Label, Location, Formation, Fire, Treatment, Area, Effort, Sample.Label) %>% 
  distinct()
```

**Comment by Josh-Lee1** [comment]
Hey @wcornwell,
I'm trying to remember how writing functions work so that I can apply the code we made on Wednesday to all the species. 
This is what I have... 

process <- function(species_name, sites.=sites, birds.=birds){
  oo <- birds %>% dplyr::filter(Species== species_name)
  woom<-ds(data = oo,truncation = 400,key="hn",monotonicity = "strict")
  oo %>%
    right_join(sites,c("Region.Label", "Location", "Formation", "Fire",  "Treatment","Sample.Label","Effort","Area"))->pp
  out<-dht2(woom,flatfile=pp,strat_formula=~Treatment)
  out1 <- pp %>% 
    select(Species, Treatment) %>% 
    na.locf() %>% 
    distinct() %>% 
    right_join(out, by = "Treatment")
  saveRDS(out1, paste0("Data/Processed/species_densities/", gsub(" ", "_", species_name), ".RDS"))
}

map_dfr(birds, process,.id="species_name") -> output

Any tips on what I'm doing wrong...?
Thanks

**Comment by wcornwell** [comment]
this doesn't do everything you're aiming for, but it runs:

```{r}
process <- function(species_name,  birds_in, sites_in) {
  birds_in %>% filter(Species == species_name) -> oo
  woom <-
    ds(
      data = oo,
      truncation = 400,
      key = "hn",
      monotonicity = "strict"
    )
  oo %>%
    right_join(
      sites_in,
      c(
        "Region.Label",
        "Location",
        "Formation",
        "Fire",
        "Treatment",
        "Sample.Label",
        "Effort",
        "Area"
      )
    ) -> pp
  out <- dht2(woom,
              flatfile = pp,
              strat_formula =  ~ Treatment)
  return(out)
}

process("Wompoo Fruit-Dove", birds, sites) # check code works on one species

#construct list of species to run over 
birds %>% group_by(Species) %>% 
  summarize(tot = sum(Count)) %>% filter(tot > 4) -> bird_sum #or something, probably should be a bigger number

bird_list <- as.list(bird_sum$Species) #lapply needs a list, map doesn't
all_birds <-
  lapply(bird_list, process, birds_in = birds, sites_in = sites)

```

i'm not good at map, so i always default back to lapply. i'm sure there is a more elegant solution with map

for building functions, always check first that it works on one element, before scaling up to the whole list...

**Comment by Josh-Lee1** [comment]
Hey @wcornwell 
I've been playing with convert_units() trying to figure out what it's doing... 
If I put in metre, minute, square metre for : distance_units, effort_units, area_units
I get: 0.0002908882

Is this the conversion factor that I can apply to abundance that will transform to density??? (birds/m^2/10min)
Don't know what we are converting to...?

**Comment by wcornwell** [comment]
me neither.  

i'm guessing that's 0.0002908882 birds/m2 (no time unit). or roughly 3 birds per hectare

i think it's modelling the absolute density based on the distances and assumes the birds are just circulating randomly.  so time doesn't come into it?  

Maybe?

**Comment by wcornwell** [comment]
https://distancesampling.org/whatisds.html
