### ISSUE TITLE
Density Units

### ISSUE THREAD

**Issue by Josh-Lee1** [Josh-Lee1/JL_honours#9]
Hey @wcornwell, 
So actually looks like the density Lmer models also have strange units. I recall they were explicit in that density means things/m^2 but our scales are wrong because we have estimated 900 birds/ha haha. 
I don't think that playing with the effort/area inputs will change the results but I will read over the documentation today to see if I've made a mistake somewhere. 
It makes sense to fix this first. 

![image](https://user-images.githubusercontent.com/59299694/116489204-b9964480-a8d7-11eb-9941-ac06b1f2afbb.png)

**Comment by wcornwell** [comment]
Try changing all input units to km or km^2.  It's coming back to me now that Charlotte Mills also found this behavior for kangaroo density, and in the end we decided it was either a bug in the package or there is something we couldn't find to make it behave with any other units?

**Comment by Josh-Lee1** [comment]
Yeah that definitely gives better numbers... But I still don't quite understand how its working. 
Trying to make sense of this confusing paragraph: 

From documentation: 
Units
In extrapolating to the entire survey region it is important that the unit measurements be consistent
or converted for consistency. A conversion factor can be specified with the convert.units variable. The values of Area in region.table, must be made consistent with the units for Effort in
sample.table and the units of distance in the data.frame that was analyzed. It is easiest if the
units of Area are the square of the units of Effort and then it is only necessary to convert the units
of distance to the units of Effort. For example, if Effort was entered in kilometres and Area in
square kilometres and distance in metres then using convert.units=0.001 would convert metres
to kilometres, density would be expressed in square kilometres which would then be consistent with
units for Area. However, they can all be in different units as long as the appropriate composite value
for convert.units is chosen. Abundance for a survey region can be expressed as: A*N/a where A
is Area for the survey region, N is the abundance in the covered (sampled) region, and a is the area
of the sampled region and is in units of Effort * distance. The sampled region a is multiplied
by convert.units, so it should be chosen such that the result is in the same units as Area. For
example, if Effort was entered in kilometres, Area in hectares (100m x 100m) and distance in
metres, then using convert.units=10 will convert a to units of hectares (100 to convert metres to
100 metres for distance and .1 to convert km to 100m units).

From this I am guessing that our effort units are a bit funny because their examples are in Kms, where mine should be 10 minutes?
Also I think that my Area units are wrong because I think that the area should describe the true population area (or strata) rather than the sampled area e.g area of all burnt rainforest I am trying to make assumptions about, not just the area of my plots...

**Comment by Josh-Lee1** [comment]
Ah no sorry I think that's what I was doing re area units, but area was in kms and distance was in ms. 
I also changed effort from 1 to 10 for all plots: 

![image](https://user-images.githubusercontent.com/59299694/116504377-78b02700-a8fb-11eb-8e34-081a49712c19.png)

These units should be # birds ber km^2

**Comment by Josh-Lee1** [comment]
Sorry for spamming messages. 
I now think that these units are the estimated 'true abundance' of each species in the same area that was sampled (e.g: 20 burnt rainforest plots x 31.41593m^2 (one plot with 100m radius) =  628) So density/km^2 should be the model output/628...?
:

![RF_Species](https://user-images.githubusercontent.com/59299694/116508632-1b20d800-a905-11eb-9af9-c4599af98770.png)

Does this make sense? one Brown Gerygone per hectare?
